In [71]:
import anndata as ad
import numpy as np 
import pandas as pd
import scipy
from scipy.sparse import csr_matrix
import scanpy as sc
print(ad.__version__)

0.11.3

In [ ]:
# Load in data
data = ad.read_h5ad(r'/root/capsule/data/AD-Group/MTG/balanced_SEAAD_MTG_RNAseq_Singleome_final-nuclei.2024-06-18.h5ad')

In [14]:
print(data)
print(f'Shape: {data.shape}')

AnnData object with n_obs × n_vars = 139000 × 36601
    obs: 'sample_id', 'Neurotypical reference', 'Donor ID', 'Organism', 'Brain Region', 'Sex', 'Gender', 'Age at Death', 'Race (choice=White)', 'Race (choice=Black/ African American)', 'Race (choice=Asian)', 'Race (choice=American Indian/ Alaska Native)', 'Race (choice=Native Hawaiian or Pacific Islander)', 'Race (choice=Unknown or unreported)', 'Race (choice=Other)', 'specify other race', 'Hispanic/Latino', 'Highest level of education', 'Years of education', 'PMI', 'Fresh Brain Weight', 'Brain pH', 'Overall AD neuropathological Change', 'Thal', 'Braak', 'CERAD score', 'Overall CAA Score', 'Highest Lewy Body Disease', 'Total Microinfarcts (not observed grossly)', 'Total microinfarcts in screening sections', 'Atherosclerosis', 'Arteriolosclerosis', 'LATE', 'Cognitive Status', 'Last CASI Score', 'Interval from last CASI in months', 'Last MMSE Score', 'Interval from last MMSE in months', 'Last MOCA Score', 'Interval from last MOCA in months', 'APOE Genotype', 'Primary Study Name', 'Secondary Study Name', 'NeuN positive fraction on FANS', 'RIN', 'cell_prep_type', 'facs_population_plan', 'rna_amplification', 'sample_name', 'sample_quantity_count', 'expc_cell_capture', 'method', 'pcr_cycles', 'percent_cdna_longer_than_400bp', 'rna_amplification_pass_fail', 'amplified_quantity_ng', 'load_name', 'library_prep', 'library_input_ng', 'r1_index', 'avg_size_bp', 'quantification_fmol', 'library_prep_pass_fail', 'exp_component_vendor_name', 'batch_vendor_name', 'experiment_component_failed', 'alignment', 'Genome', 'ar_id', 'bc', 'GEX_Estimated_number_of_cells', 'GEX_number_of_reads', 'GEX_sequencing_saturation', 'GEX_Mean_raw_reads_per_cell', 'GEX_Q30_bases_in_barcode', 'GEX_Q30_bases_in_read_2', 'GEX_Q30_bases_in_UMI', 'GEX_Percent_duplicates', 'GEX_Q30_bases_in_sample_index_i1', 'GEX_Q30_bases_in_sample_index_i2', 'GEX_Reads_with_TSO', 'GEX_Sequenced_read_pairs', 'GEX_Valid_UMIs', 'GEX_Valid_barcodes', 'GEX_Reads_mapped_to_genome', 'GEX_Reads_mapped_confidently_to_genome', 'GEX_Reads_mapped_confidently_to_intergenic_regions', 'GEX_Reads_mapped_confidently_to_intronic_regions', 'GEX_Reads_mapped_confidently_to_exonic_regions', 'GEX_Reads_mapped_confidently_to_transcriptome', 'GEX_Reads_mapped_antisense_to_gene', 'GEX_Fraction_of_transcriptomic_reads_in_cells', 'GEX_Total_genes_detected', 'GEX_Median_UMI_counts_per_cell', 'GEX_Median_genes_per_cell', 'Multiome_Feature_linkages_detected', 'Multiome_Linked_genes', 'Multiome_Linked_peaks', 'ATAC_Confidently_mapped_read_pairs', 'ATAC_Fraction_of_genome_in_peaks', 'ATAC_Fraction_of_high_quality_fragments_in_cells', 'ATAC_Fraction_of_high_quality_fragments_overlapping_TSS', 'ATAC_Fraction_of_high_quality_fragments_overlapping_peaks', 'ATAC_Fraction_of_transposition_events_in_peaks_in_cells', 'ATAC_Mean_raw_read_pairs_per_cell', 'ATAC_Median_high_quality_fragments_per_cell', 'ATAC_Non-nuclear_read_pairs', 'ATAC_Number_of_peaks', 'ATAC_Percent_duplicates', 'ATAC_Q30_bases_in_barcode', 'ATAC_Q30_bases_in_read_1', 'ATAC_Q30_bases_in_read_2', 'ATAC_Q30_bases_in_sample_index_i1', 'ATAC_Sequenced_read_pairs', 'ATAC_TSS_enrichment_score', 'ATAC_Unmapped_read_pairs', 'ATAC_Valid_barcodes', 'Number of mapped reads', 'Number of unmapped reads', 'Number of multimapped reads', 'Number of reads', 'Number of UMIs', 'Genes detected', 'Doublet score', 'Fraction mitochondrial UMIs', 'Used in analysis', 'Class confidence', 'Class', 'Subclass confidence', 'Subclass', 'Supertype confidence', 'Supertype (non-expanded)', 'Supertype', 'Continuous Pseudo-progression Score', 'Severely Affected Donor'
    obsm: 'X_scVI', 'X_umap'
    layers: 'UMIs'
Shape: (139000, 36601)

In [15]:
print(data.obs_names[:5])
print(data.var_names[:5])

Index(['Cell_0', 'Cell_1', 'Cell_2', 'Cell_3', 'Cell_4'], dtype='object')
Index(['MIR1302-2HG', 'FAM138A', 'OR4F5', 'AL627309.1', 'AL627309.3'], dtype='object')

In [26]:
# obs
print(data.obs.head())
print(data.obs.columns)

df = pd.DataFrame(data = data.obs)

                                             sample_id Neurotypical reference  \
Cell_0  CATCAAGTCGGATACT-L8TX_210729_01_G12-1153814338                  False
Cell_1  TGCTGAAAGCGATCGA-L8TX_210415_01_E11-1153814186                  False
Cell_2             AAGCCATGTGATATAG-LKTX_191204_01_F01                   True
Cell_3  TCGATTTGTCGTGATT-L8TX_210715_01_D05-1153814295                  False
Cell_4  CGCCAGATCAACCTTT-L8TX_210722_01_B07-1153814297                  False

          Donor ID Organism Brain Region     Sex  Gender  Age at Death  \
Cell_0  H21.33.035    human    Human MTG  Female  Female          97.0
Cell_1  H21.33.007    human    Human MTG  Female  Female          86.0
Cell_2  H19.30.001    human    Human MTG    Male    Male           NaN
Cell_3  H20.33.032    human    Human MTG    Male    Male          98.0
Cell_4  H20.33.034    human    Human MTG  Female  Female          85.0

       Race (choice=White) Race (choice=Black/ African American)  ...  \
Cell_0             Checked                             Unchecked  ...
Cell_1             Checked                             Unchecked  ...
Cell_2           Reference                             Reference  ...
Cell_3             Checked                             Unchecked  ...
Cell_4             Checked                             Unchecked  ...

       Used in analysis Class confidence                        Class  \
Cell_0             True              1.0  Non-neuronal and Non-neural
Cell_1             True              1.0  Non-neuronal and Non-neural
Cell_2             True              1.0  Non-neuronal and Non-neural
Cell_3             True              1.0  Non-neuronal and Non-neural
Cell_4             True              1.0  Non-neuronal and Non-neural

       Subclass confidence         Subclass Supertype confidence  \
Cell_0            1.000000  Oligodendrocyte             1.000000
Cell_1            1.000000  Oligodendrocyte             1.000000
Cell_2            1.000000  Oligodendrocyte             1.000000
Cell_3            0.999693  Oligodendrocyte             0.999982
Cell_4            1.000000  Oligodendrocyte             1.000000

       Supertype (non-expanded) Supertype Continuous Pseudo-progression Score  \
Cell_0                  Oligo_4   Oligo_4                            0.376970
Cell_1                  Oligo_4   Oligo_4                            0.723364
Cell_2                  Oligo_4   Oligo_4                                 NaN
Cell_3                  Oligo_4   Oligo_4                            0.818041
Cell_4                  Oligo_4   Oligo_4                            0.368330

       Severely Affected Donor
Cell_0                       N
Cell_1                       N
Cell_2                     NaN
Cell_3                       N
Cell_4                       N

[5 rows x 135 columns]
Index(['sample_id', 'Neurotypical reference', 'Donor ID', 'Organism',
       'Brain Region', 'Sex', 'Gender', 'Age at Death', 'Race (choice=White)',
       'Race (choice=Black/ African American)',
       ...
       'Used in analysis', 'Class confidence', 'Class', 'Subclass confidence',
       'Subclass', 'Supertype confidence', 'Supertype (non-expanded)',
       'Supertype', 'Continuous Pseudo-progression Score',
       'Severely Affected Donor'],
      dtype='object', length=135)

In [72]:
df = pd.DataFrame(data.X.toarray() if scipy.sparse.issparse(data.X) else data.X, 
                 index=data.obs_names, 
                 columns=data.var_names)

df.head()

MemoryError: Unable to allocate 19.0 GiB for an array with shape (139000, 36601) and data type float32

_____

In [ ]:
data.obs['Supertype']

exp_component_name
CATCAAGTCGGATACT-L8TX_210729_01_G12-1153814338                          Oligo_4
TGCTGAAAGCGATCGA-L8TX_210415_01_E11-1153814186                          Oligo_4
AAGCCATGTGATATAG-LKTX_191204_01_F01-1156636535                          Oligo_4
TCGATTTGTCGTGATT-L8TX_210715_01_D05-1153814295                          Oligo_4
CGCCAGATCAACCTTT-L8TX_210722_01_B07-1153814297                          Oligo_4
                                                                         ...
TTCATGTTCAGTCACA-L8TX_210430_01_C04-1142430413_aug_2cells_comb_814-1     Endo_1
ATCGCCTAGTCTGCAT-L8TX_210430_01_D05-1142430407_aug_2cells_comb_815-1     Endo_1
CCGAACGAGAGTCTGG-L8TX_210430_01_C04-1142430413_aug_2cells_comb_816-1     Endo_1
GTGAGGATCACTCCGT-L8TX_201030_01_B12-1142430231_aug_2cells_comb_817-1     Endo_1
CGCCAGAAGGTACCTT-L8TX_210729_01_C12-1153814340_aug_2cells_comb_818-1     Endo_1
Name: Supertype, Length: 139000, dtype: category
Categories (139, object): ['Astro_1', 'Astro_2', 'Astro_3', 'Astro_4', ..., 'Vip_18', 'Vip_19', 'Vip_21', 'Vip_23']

In [17]:
data.obs_names = [f"Cell_{i:d}" for i in range(data.n_obs)]
data.var_names = [f"Gene_{i:d}" for i in range(data.n_vars)]
print(data.obs_names[:10])

Index(['Cell_0', 'Cell_1', 'Cell_2', 'Cell_3', 'Cell_4', 'Cell_5', 'Cell_6',
       'Cell_7', 'Cell_8', 'Cell_9'],
      dtype='object')

In [21]:
data.to_df()

,Gene_0,Gene_1,Gene_2,Gene_3,Gene_4,Gene_5,Gene_6,Gene_7,Gene_8,Gene_9,...,Gene_36591,Gene_36592,Gene_36593,Gene_36594,Gene_36595,Gene_36596,Gene_36597,Gene_36598,Gene_36599,Gene_36600
Cell_0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cell_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cell_2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cell_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cell_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cell_138995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cell_138996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cell_138997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cell_138998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Cell_138999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0